[package]
name = "dummy-lib"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"
description = "Dummy library crate for testing"
repository = "https://github.com/lovesegfault/dummy-rs"
authors = ["Bernardo Meurer <bernardo@meurer.org>"]

[dependencies]
