[package]
name = "dummy-bin"
description = "Dummy binary crate for testing"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
